In [3]:
import numpy as np

In [4]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [5]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [6]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
a[0]

array([1, 2, 3, 4])

In [8]:
a[(0,1)]

2

In [9]:
print(a[0])

[1 2 3 4]


In [10]:
import numpy as np
a = np.array([1, 2, 3])

In [11]:
a

array([1, 2, 3])

In [12]:
a[:]

array([1, 2, 3])

In [13]:
a[np.newaxis, :]

array([[1, 2, 3]])

In [14]:
a2=a[np.newaxis, :]

In [15]:
a2.shape

(1, 3)

In [16]:
a.shape

(3,)

In [17]:
a=np.array([1,2,3])

In [18]:
np.zeros(2)

array([0., 0.])

In [19]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [20]:
np.ones(3)

array([1., 1., 1.])

In [21]:
np.ones(30)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
np.empty(2)

array([0., 0.])

In [33]:
np.arange(4)

array([0, 1, 2, 3])

In [34]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [35]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [52]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

In [53]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [54]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
a = np.array([3, 1, 2])
np.argsort(a)

array([1, 2, 0], dtype=int64)

In [56]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
ind = np.lexsort((first_names, surnames))
ind

array([1, 2, 0], dtype=int64)

In [57]:
np.searchsorted([1,2,3,4,5], 3)

2

In [58]:
np.searchsorted([1,2,3,4,5], 3, side='right')

3

In [59]:
np.searchsorted([1,2,3,4,5], [-10, 10, 2, 3])

array([0, 5, 1, 2], dtype=int64)

In [60]:
a = np.array([7, 1, 7, 7, 1, 5, 7, 2, 3, 2, 6, 2, 3, 0])
p = np.partition(a, 4)
p

array([0, 1, 2, 1, 2, 5, 2, 3, 3, 6, 7, 7, 7, 7])

In [61]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [62]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [63]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [64]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [67]:
x

array([[1, 2],
       [3, 4]])

In [66]:
y

array([[5, 6]])

In [5]:
import numpy as np

In [6]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [7]:
array_example.ndim

3

In [8]:
array_example.size

24

In [10]:
array_example.shape

(3, 2, 4)

In [12]:
import numpy as np
a = np.arange(6)

In [13]:
a

array([0, 1, 2, 3, 4, 5])

In [14]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [16]:
print(a)

[0 1 2 3 4 5]


In [17]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [18]:
a=np.array([1,2,3,4,5,6])

In [93]:
a.shape

(6,)

In [19]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [21]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [23]:
a[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [22]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [24]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [25]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [26]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [27]:
data = np.array([1, 2, 3])

In [29]:
data[1]

2

In [30]:
data[0:2]

array([1, 2])

In [31]:
data[1:]

array([2, 3])

In [32]:
data[-2:]

array([2, 3])

In [33]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [34]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
a[a<5]

array([1, 2, 3, 4])

In [37]:
a<5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [38]:
a>5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [39]:
a>=5

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [40]:
a[a>=5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [43]:
print(a[a < 5])

[1 2 3 4]


In [44]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [46]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [47]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [48]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [49]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [50]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [51]:
print(a[b])

[1 2 3 4]


In [52]:
list_of_coordinates

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [53]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [54]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [56]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])

In [57]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [58]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [59]:
a1

array([[1, 1],
       [2, 2]])

In [60]:
a2

array([[3, 3],
       [4, 4]])

In [71]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [72]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [73]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [74]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [75]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [76]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [77]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
b2 = a.copy()

In [82]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [83]:
data - ones

array([0, 1])

In [84]:
data * data

array([1, 4])

In [86]:
data / data

array([1., 1.])

In [87]:
a = np.array([1, 2, 3, 4])

In [88]:
a.sum()

10

In [89]:
b=[1,321,3,4]

In [90]:
len(b)

4

In [91]:
b.sort()

In [92]:
b

[1, 3, 4, 321]

In [93]:
b = np.array([[1, 1], [2, 2]])

In [94]:
b.sum(axis=0)

array([3, 3])

In [95]:
b.sum(axis=1)

array([2, 4])

In [98]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [99]:
data.max()

2.0

In [100]:
data.min()

1.0

In [101]:
data.sum()

3.0

In [102]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [103]:
a.sum()

4.8595784

In [104]:
a.min()

0.05093587

In [105]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [106]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [107]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [108]:
data[0, 1]

2

In [109]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [110]:
data[0:2, 0]

array([1, 3])

In [111]:
data.max()

6

In [112]:
data.min()

1

In [113]:
data.sum()

21

In [114]:
data = np.array([[1, 2], [5, 3], [4, 6]])

In [115]:
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [116]:
data.max(axis=0)

array([5, 6])

In [117]:
data.max(axis=1)

array([2, 5, 6])

In [118]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [119]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [122]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [123]:
np.ones(3)

array([1., 1., 1.])

In [124]:
np.zeros(3)

array([0., 0., 0.])

In [126]:
rng = np.random.default_rng() 
rng.random(3) 

array([0.46593743, 0.17261375, 0.41429993])

In [127]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [128]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [129]:
rng.random((3, 2)) 

array([[0.49501644, 0.80727831],
       [0.51615837, 0.83604444],
       [0.35284451, 0.54408003]])

In [130]:
rng.integers(5, size=(2, 4))

array([[2, 0, 1, 4],
       [1, 1, 1, 4]], dtype=int64)

In [131]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [132]:
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [133]:
np.unique(a, return_index=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14], dtype=int64))

In [134]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [135]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [136]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [138]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [139]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [140]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [141]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [142]:
print(indices)

[0 1 2]


In [144]:
print(occurrence_count)

[2 1 1]


In [145]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [146]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [147]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [148]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [149]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [150]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [151]:
reversed_arr = np.flip(arr)

In [152]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [153]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [154]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [155]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [156]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [157]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [158]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [159]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [160]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [162]:
a1 = x.flatten()
a1[0] = 99

In [163]:
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [164]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [166]:
a2 = x.ravel()
a2[0] = 98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [167]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
